### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Kediel** [Kediel/Violent-Python#2]
password refused
[-] Error Connecting
could not set shell prompt (received: "unset PROMPT_COMMAND\r\nPS1='[PEXPECT]\\$ '\r\nset prompt='[PEXPECT]\\$ '\r\n", expected: '\\[PEXPECT\\][\\$\\#] ').
[-] Error Connecting
Traceback (most recent call last):
  File "botNet.py", line 49, in <module>
    botnetCommand('uname -v')
  File "botNet.py", line 36, in botnetCommand
    output = client.send_command(command)
  File "botNet.py", line 28, in send_command
    self.session.sendline(cmd)
AttributeError: 'NoneType' object has no attribute 'sendline'

**Comment by besnardf** [comment]
It seems that your session is empty.
Are you sure you have the correct host / username / password for the SSH session ? (I suppose it's SSH)

**Comment by Kediel** [comment]
Yes, I used the correct information.  The problem was with the user I was trying to SSH. I tried a different user and the script worked fine.
